FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/keys ./keys
COPY --from=builder /app/.env .env

ENV PORT=3000
EXPOSE 3000
CMD ["npm", "run", "start"]
